-- Create projects table
CREATE TABLE public.projects (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  brief TEXT NOT NULL,
  image TEXT NOT NULL,
  category TEXT NOT NULL,
  year TEXT NOT NULL,
  techniques TEXT[] NOT NULL DEFAULT '{}',
  responsibilities TEXT[] NOT NULL DEFAULT '{}',
  tools TEXT[] NOT NULL DEFAULT '{}',
  description TEXT NOT NULL,
  challenge TEXT NOT NULL,
  solution TEXT NOT NULL,
  outcome TEXT NOT NULL,
  images TEXT[] NOT NULL DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

-- Create policy to allow everyone to read projects (public portfolio)
CREATE POLICY "Anyone can view projects" 
ON public.projects 
FOR SELECT 
USING (true);

-- Create policy to allow authenticated users to manage projects (for you as the admin)
CREATE POLICY "Authenticated users can manage projects" 
ON public.projects 
FOR ALL 
USING (auth.uid() IS NOT NULL);

-- Create function to update timestamps
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for automatic timestamp updates
CREATE TRIGGER update_projects_updated_at
BEFORE UPDATE ON public.projects
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- Insert all the projects data
INSERT INTO public.projects (id, title, brief, image, category, year, techniques, responsibilities, tools, description, challenge, solution, outcome, images) VALUES
('wearable-adoption-research', 'Wearable Adoption Research', 'Investigated low adoption of elder-care wearables through behavior-driven design.', 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80', 'Healthcare', '2024', ARRAY['User Research', 'Ethnographic Studies', 'Heuristic Evaluation', 'Accessibility Design'], ARRAY['UX Researcher', 'Lead Designer', 'User Research Lead'], ARRAY['Figma', 'UserTesting', 'NVDA', 'Survey Tools'], 'Investigated low engagement in elder-care wearable tech through ethnographic research and heuristic audits. Identified issues in accessibility, onboarding, and complexity. Recommended voice-guided onboarding, caregiver dashboards, and simplified flows. Post-redesign testing confirmed increased sustained usage and satisfaction.', 'Elder-care wearables showed consistently low adoption rates despite clear health benefits.', 'Conducted ethnographic research and accessibility audits to identify barriers, then designed voice-guided onboarding and caregiver dashboards.', 'Post-redesign testing confirmed increased sustained usage and satisfaction among elderly users.', ARRAY['https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?auto=format&fit=crop&w=800&q=80']),

('non-wearable-fall-detection', 'Non-Wearable Fall Detection', 'Explored passive sensor solutions like Wi-Fi and thermal for fall detection.', 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80', 'Healthcare', '2024', ARRAY['IoT Design', 'Dashboard Design', 'Sensor UX', 'Alert Systems'], ARRAY['UX Manager', 'IoT UX Specialist', 'Product Strategist'], ARRAY['Figma', 'Principle', 'IoT Sensors', 'Data Analytics'], 'Explored ambient sensor tech such as Wi-Fi, radar, and thermal for fall detection without wearable reliance. Designed dashboards for caregivers with alert tuning and summaries. Wi-Fi emerged as the optimal tech. Solution reduced false alerts and improved user trust.', 'Traditional wearable fall detection had low compliance rates and frequent false alarms.', 'Designed ambient sensor solutions using Wi-Fi, radar, and thermal technology with intelligent alert systems.', 'Wi-Fi emerged as optimal solution, reducing false alerts and improving user trust significantly.', ARRAY['https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80']),

('voice-of-customer-analytics', 'Voice of Customer Analytics', 'Transformed raw customer feedback into an actionable UX roadmap using NLP.', 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80', 'Data Analytics', '2023', ARRAY['NLP Analysis', 'Data Visualization', 'Workshop Facilitation', 'Usability Testing'], ARRAY['UX Manager', 'Data UX Lead', 'Research Lead'], ARRAY['Python', 'Tableau', 'Miro', 'Figma'], 'Processed multi-channel feedback using NLP and clustering to extract key UX pain points. Identified 5 focus modules. Used workshops to align product teams, built prototypes, and validated redesigns through usability testing. Resulted in phased rollout plan based on user feedback.', 'Raw customer feedback across multiple channels was overwhelming and difficult to act upon.', 'Implemented NLP processing and clustering to identify key pain points, then facilitated workshops to align teams.', 'Successfully identified 5 focus modules and created a phased rollout plan based on validated user feedback.', ARRAY['https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?auto=format&fit=crop&w=800&q=80']),

('enterprise-portal-ux-audit', 'Enterprise Portal UX Audit', 'Redesigned a legacy enterprise portal with personalized dashboards and improved navigation.', 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?auto=format&fit=crop&w=800&q=80', 'Enterprise', '2023', ARRAY['UX Audit', 'Information Architecture', 'Dashboard Design', 'Enterprise UX'], ARRAY['UX Manager', 'Sr. Designer', 'Enterprise UX Lead'], ARRAY['Figma', 'Miro', 'UserTesting', 'Analytics'], 'Mapped workflows, interviewed key personas, and benchmarked enterprise dashboards. Identified inefficiencies in search, roles, and entitlements. Proposed a modular UX redesign with contextual cards and search-first IA. Achieved higher task success and reduced friction.', 'Legacy enterprise portal had inefficient workflows and poor user experience for key personas.', 'Conducted comprehensive workflow mapping and persona interviews, then redesigned with modular UX and search-first architecture.', 'Achieved significantly higher task success rates and reduced user friction across all workflows.', ARRAY['https://images.unsplash.com/photo-1531297484001-80022131f5a1?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?auto=format&fit=crop&w=800&q=80']),

('user-onboarding-redesign', 'User Onboarding Redesign', 'Boosted onboarding conversion by streamlining multi-step user flows.', 'https://images.unsplash.com/photo-1649972904349-6e44c42644a7?auto=format&fit=crop&w=800&q=80', 'SaaS', '2023', ARRAY['Onboarding Design', 'A/B Testing', 'User Flow Optimization', 'Conversion Analytics'], ARRAY['UX Manager', 'Conversion Specialist', 'User Research Lead'], ARRAY['Figma', 'Hotjar', 'Optimizely', 'Google Analytics'], 'Analyzed drop-offs and user rage-click data. Redesign focused on contextual help, smart defaults, and social login options. A/B tested prototypes and achieved a 60% increase in successful onboarding. Support tickets dropped significantly.', 'High drop-off rates during user onboarding with evidence of user frustration and rage-clicks.', 'Redesigned with contextual help, smart defaults, and social login options, then A/B tested all changes.', '60% increase in successful onboarding completion and significant reduction in support tickets.', ARRAY['https://images.unsplash.com/photo-1649972904349-6e44c42644a7?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?auto=format&fit=crop&w=800&q=80']),

('access-management-dashboard', 'Access Management Dashboard', 'Simplified complex entitlement workflows through role-based dashboard UX.', 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?auto=format&fit=crop&w=800&q=80', 'Enterprise', '2022', ARRAY['Dashboard Design', 'Role-Based UX', 'Tree Testing', 'Enterprise Workflows'], ARRAY['UX Manager', 'Enterprise UX Lead', 'Information Architect'], ARRAY['Figma', 'OptimalSort', 'UserTesting', 'Miro'], 'UX review revealed overwhelming permissions layout. Introduced grouped roles, batch actions, and search filter logic. Tree testing confirmed ease of use. Stakeholders adopted the system with improved confidence and fewer support requests.', 'Complex permission management system was overwhelming users and generating support requests.', 'Redesigned with grouped roles, batch actions, and improved search filter logic validated through tree testing.', 'Stakeholders gained confidence in the system and support requests decreased significantly.', ARRAY['https://images.unsplash.com/photo-1605810230434-7631ac76ec81?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80']),

('ai-powered-assistant', 'AI-Powered Assistant for Call Agents', 'Designed real-time suggestion engine using live call context and nudges.', 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80', 'AI/ML', '2022', ARRAY['AI UX Design', 'Real-time Systems', 'Wizard-of-Oz Testing', 'Cognitive Load Design'], ARRAY['UX Manager', 'AI UX Specialist', 'User Research Lead'], ARRAY['Figma', 'Principle', 'Voice Analytics', 'A/B Testing'], 'Built a contextual suggestion interface that listens to live calls and proposes next actions. Used Wizard-of-Oz studies and mapped mental models. Focused on minimal cognitive load and non-intrusive prompts. Reduced call handling time measurably.', 'Call agents needed real-time assistance without adding cognitive load during live conversations.', 'Designed contextual AI assistant with non-intrusive prompts, validated through Wizard-of-Oz studies.', 'Measurably reduced call handling time while maintaining call quality and agent satisfaction.', ARRAY['https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80']),

('chatbot-ui-modernization', 'Chatbot UI Modernization', 'Refreshed chatbot UX with improved readability, hierarchy, and natural interaction flows.', 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=800&q=80', 'Conversational UX', '2022', ARRAY['Conversational Design', 'Accessibility Audit', 'Visual Design', 'Interaction Flow'], ARRAY['UX Manager', 'Conversation Designer', 'Accessibility Lead'], ARRAY['Figma', 'Voiceflow', 'Accessibility Tools', 'User Testing'], 'Evaluated a legacy chatbot for accessibility, tone, and continuity. Redesigned UI with collapsible conversation threads, persona avatars, and dynamic replies. Refreshed visual system increased chat completion and re-engagement rates.', 'Legacy chatbot had poor accessibility, unclear tone, and low completion rates.', 'Complete UI redesign with collapsible threads, persona avatars, and improved visual hierarchy.', 'Increased chat completion and re-engagement rates significantly after visual system refresh.', ARRAY['https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?auto=format&fit=crop&w=800&q=80']),

('multi-site-ordering', 'Multi-Site Ordering for Franchisees', 'Built one-click ordering across locations with smart filtering and tracking.', 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?auto=format&fit=crop&w=800&q=80', 'E-commerce', '2021', ARRAY['Multi-location UX', 'Dashboard Design', 'Order Management', 'Bulk Operations'], ARRAY['UX Manager', 'E-commerce UX Lead', 'Product Designer'], ARRAY['Figma', 'UserTesting', 'Analytics', 'Prototyping'], 'Pain points in multi-location bulk ordering led to confusion and tracking errors. Designed a one-click dashboard with visual summaries, search filters, and order tracking widgets. Operational clarity improved dramatically.', 'Multi-location bulk ordering caused confusion and tracking errors for franchisees.', 'Designed unified dashboard with visual summaries, smart filters, and comprehensive order tracking.', 'Operational clarity improved dramatically with reduced errors and faster order processing.', ARRAY['https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1649972904349-6e44c42644a7?auto=format&fit=crop&w=800&q=80']),

('device-setup-companion', 'Device Setup Companion (OPTG)', 'Created guided assistant to simplify first-time hardware setup.', 'https://images.unsplash.com/photo-1473091534298-04dcbce3278c?auto=format&fit=crop&w=800&q=80', 'Hardware UX', '2021', ARRAY['Setup Flows', 'Guided Assistance', 'Animation Design', 'Hardware UX'], ARRAY['UX Manager', 'Hardware UX Lead', 'Interaction Designer'], ARRAY['Figma', 'After Effects', 'Principle', 'User Testing'], 'Analyzed onboarding pain for hardware setup. Introduced modular setup assistant, inline help, and animated guidance. Task completion times dropped significantly and first-time success rates increased post-deployment.', 'Hardware setup process was complex and led to high support call volumes.', 'Created modular setup assistant with inline help and animated step-by-step guidance.', 'Task completion times dropped significantly with increased first-time success rates.', ARRAY['https://images.unsplash.com/photo-1473091534298-04dcbce3278c?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?auto=format&fit=crop&w=800&q=80']),

('smart-setup-optimization', 'Smart Setup Optimization', 'Reduced setup drop-offs by optimizing transfer flow and adding predictive UX elements.', 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80', 'Hardware UX', '2020', ARRAY['Predictive UX', 'Recovery Flows', 'Progress Indicators', 'Smart Defaults'], ARRAY['UX Manager', 'Product Designer', 'User Research Lead'], ARRAY['Figma', 'Hotjar', 'User Testing', 'Analytics'], 'Users often abandoned during device transfers. Improved recovery checkpoints, introduced predictive feedback, and allowed progress saving. User satisfaction scores and completion rates showed major uptick.', 'High abandonment rates during device transfer processes with poor recovery options.', 'Added recovery checkpoints, predictive feedback, and progress saving capabilities.', 'Major improvement in user satisfaction scores and completion rates.', ARRAY['https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80']),

('universal-shopping-cart', 'Universal Shopping Cart', 'Enabled persistent cross-device cart with real-time SKU logic and checkout syncing.', 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?auto=format&fit=crop&w=800&q=80', 'E-commerce', '2020', ARRAY['Cross-device UX', 'Real-time Sync', 'SKU Management', 'Progressive Enhancement'], ARRAY['UX Manager', 'E-commerce Lead', 'Technical UX Designer'], ARRAY['Figma', 'Real-time APIs', 'A/B Testing', 'Analytics'], 'Persistent cart and stock sync issues were frequent. Enabled real-time SKU substitutions, cross-device session continuity, and alert messaging. Checkout rates improved across all channels.', 'Cart persistence and stock synchronization issues across devices caused checkout abandonment.', 'Implemented real-time SKU substitutions, cross-device continuity, and proactive alert messaging.', 'Checkout rates improved significantly across all channels and devices.', ARRAY['https://images.unsplash.com/photo-1531297484001-80022131f5a1?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?auto=format&fit=crop&w=800&q=80']);